export const Icons = {
  Splash: require('../assets/images/Splash.png'),
  Home: require('../assets/images/Home.png'),
  // Ticket: require('../assets/images/Ticket.png'),
  user: require('../assets/images/user.png'),
  // human: require('../assets/images/human.png'),
  button: require('../assets/images/button.png'),
  Grouphuman: require('../assets/images/Grouphuman.png'),

  rightarrow: require('../assets/images/rightarrow.png'),

  security: require('../assets/images/security.png'),
  payment: require('../assets/images/payment.png'),
  cross: require('../assets/images/cross.png'),
  Logo: require('../assets/images/logo.png'),
  facebook: require('../assets/images/facebook.png'),
  apple: require('../assets/images/apple.png'),
  Calender: require('../assets/images/cal.png'),
  google: require('../assets/images/google.png'),
  Cirecle: require('../assets/images/circle.png'),
  Glass: require('../assets/images/bar.png'),
  Arrow: require('../assets/images/arrow.png'),
  BgImage: require('../assets/images/signinbg.png'),

  // Rem: require('../assets/images/toggle.png'),
  Arrow: require('../assets/images/downArrow.png'),
  Lock: require('../assets/images/lock.png'),
  // rightdouble: require('../assets/images/rightdouble.png'),
  Show: require('../assets/images/Show.png'),
  // warning: require('../assets/images/warning.png'),
  tick: require('../assets/images/tick.png'),
  hide: require('../assets/images/hide.png'),
  exit: require('../assets/images/exit.png'),
  shutdown: require('../assets/images/shutdown.png'),
  left: require('../assets/images/left.png'),
  ellipsis: require('../assets/images/ellipsis.png'),
  landingnew: require('../assets/images/landingnew.jpg'),
  Search: require('../assets/images/Search.png'),

  Whitelogo: require('../assets/images/whitelogo.png'),
  QR: require('../assets/images/QR.png'),
  friends: require('../assets/images/friends.png'),
  BARV: require('../assets/images/BARV.png'),
  Settings: require('../assets/images/Settings.png'),

  fpage: require('../assets/images/fpage.png'),
  bvpage: require('../assets/images/bvpage.png'),
  hmbgp: require('../assets/images/hmbgp.png'),
  pass: require('../assets/images/pass.png'),
  tickimg: require('../assets/images/tickimg.png'),
  shicon: require('../assets/images/shicon.png'),
  shyicon: require('../assets/images/shyicon.png'),
  humanIcon: require('../assets/images/humanIcon.png'),
  Date: require('../assets/images/Date.png'),
  arrow2: require('../assets/images/arrow2.png'),
  filter: require('../assets/images/filter.png'),
  pLove: require('../assets/images/pLove.png'),
  outlinelove: require('../assets/images/outlinelove.png'),
  Location: require('../assets/images/Location.png'),
  leftarrow2: require('../assets/images/leftarrow2.png'),
  scannercd: require('../assets/images/scannercd.png'),
  frndqr: require('../assets/images/frndqr.png'),
  Pass2: require('../assets/images/Pass2.png'),
  DefaultProfile: require('../assets/images/defaultprofile.png'),
  EditIcon: require('../assets/images/edit.png'),
  CustomMark: require('../assets/images/customMarker.png'),
  defaultBanner: require('../assets/images/defaultbanner.png'),
  addImage: require('../assets/images/addvector.png'),
  lockFriends: require('../assets/images/lockfriend.png'),
  allow:require('../assets/images/allow.png'),
  dontAllow:require('../assets/images/dontAllow.png'),
  link:require('../assets/images/link.png'),
  ImageSliderSmall:require('../assets/images/Rectangle 3246.png'),
  checkWhite:require('../assets/images/_check_.png'),
  uncheckWhite:require('../assets/images/_xletter_.png'),
  plusWhite:require('../assets/images/Vector(1).png'),
  signupImg1:require('../assets/images/barLogo.png'),
  introImg1:require('../assets/images/signupIntro1.png'),
  introImg2:require('../assets/images/signupIntro2.png'),
  introArrow:require('../assets/images/introArrow.png'),
  homearrow:require('../assets/images/downup.png')


  
};

export const Colors = {
  themeblue: '#060C30',
  bottombutton: '#8E6BF2',
  darkblue: '#030721',
  pink: '#D73F9D',
  cardview: '#0E1648',
  lightpink: '#B9A4F4',
  lightgreen: '#2AE8AB',
  yellow: '#DCE024',
  red: '#B4262C',
  orange: '#FF7A00',
  placeholder: '#39458C',

  buttoncolor: '#5652E5',
  white: '#FFFFFF',
  // placeholder:'#8A8CB3',
  yellow: '#FFCB46',
  txtcolor: '#8A8CB3',
  black: '#000000',
};

export const Fonts = {
  Poppins_Black: 'Poppins-Black',
  Poppins_BlackItalic: 'Poppins-BlackItalic',
  Poppins_Bold: 'Poppins-Bold',
  Poppins_BoldItalic: 'Poppins-BoldItalic',
  Poppins_ExtraBold: 'Poppins-ExtraBold',
  Poppins_ExtraBoldItalic: 'Poppins-ExtraBoldItalic',
  Poppins_ExtraLight: 'Poppins-ExtraLight',
  Poppins_ExtraLightItalic: 'Poppins-ExtraLightItalic',
  Poppins_Italic: 'Poppins-Italic',
  Poppins_Light: 'Poppins-Light',
  Poppins_LightItalic: 'Poppins-LightItalic',
  Poppins_Medium: 'Poppins-Medium',
  Poppins_MediumItalic: 'Poppins-MediumItalic',
  Poppins_Regular: 'Poppins-Regular',
  Poppins_SemiBold: 'Poppins-SemiBold',
  Poppins_SemiBoldItalic: 'Poppins-SemiBoldItalic',
  Poppins_Thin: 'Poppins-Thin',
  Poppins_ThinItalic: 'Poppins-ThinItalic',
};
